### ISSUE TITLE
metodo battleship

### ISSUE THREAD

**Issue by fsjacome** [peterarsentev/games_oop_javafx#10]
La interfaz ship() hereda dos métodos a la clase battleship que no son utilizados en el programa, esto puede causar que el programa sea mas grande de lo necesario y puede acumularse con otras expansiones de clase y hacerla más complicada de lo necesario.
quitar los métodos null reduce el tamaño del código y facilita la comprensión de la clase.

**Comment by peterarsentev** [comment]
@fsjacome Please use English.
