### ISSUE TITLE
Refactoring propose using Replace Exception with Test

### ISSUE THREAD

**Issue by rexman10** [peterarsentev/games_oop_javafx#15]
Location class Logic package packman
Lines 30 - 39
The whole method body is contained inside a try and catch block that launches exception in case of error and doesn't execute code logic if so.

Method State before refactoring:

![image](https://user-images.githubusercontent.com/91928959/184267980-c13883f9-62e2-4d5b-ba37-02dbf35ea599.png)

Method State after refactoring:

![image](https://user-images.githubusercontent.com/91928959/184268066-b16c4c6a-2df5-475d-a1ca-6ca27340c857.png)

**Comment by peterarsentev** [comment]
Thanks for comment. I haven't finished this game yet.
