### ISSUE TITLE
Refactoring propose using Collapse Hierarchy

### ISSUE THREAD

**Issue by rexman10** [peterarsentev/games_oop_javafx#16]
Location package ships inside package seabattle

There is an interface that defines two methods and a class Ship that implements it, but the methods that are due to override return null and are never used. Therefore this interface is unnecessary and we need to make them into one class called Ship that defines these functions and implements the behavior of the previous Ship class.

Classes State before refcactoring:

![image](https://user-images.githubusercontent.com/91928959/184269692-5de8bcf4-25ab-4776-a95b-a48cca6f1b94.png)

Classes State after refactoring:

![image](https://user-images.githubusercontent.com/91928959/184269510-9af6fa4c-68e0-4099-a3df-d52d7f0dcdbb.png)

**Comment by peterarsentev** [comment]
Thanks. I will fix it soon.
